### ISSUE TITLE
Todo list for documentation

### ISSUE THREAD

**Issue by shizejin** [QuantEcon/Games.jl#32]
- [x] Create a new section called "Base Types and Methods" which includes NormalFormGame.
- [x] Add random game to the section "Base Types and Methods".
- [x] Change `auto_doc_gen.jl`, so that each section does not have subsections for files, but just has subsections of "Exported" and "Internal".
- [x] [Add a `User Guide`](https://github.com/QuantEcon/Games.jl/pull/27#issuecomment-287337136) before Library. 
- [x] Add a description to docs/README.md about how to use auto_doc_gen.jl.

**Comment by oyamad** [comment]
* [ ] Modify the docstrings in accordance with the official documentation style, as in https://github.com/QuantEcon/Games.jl/issues/25#issuecomment-287318920.

**Comment by oyamad** [comment]
* [ ] Revise the docstrings for the repeated game related functions; see the [documentation](http://quantecon.github.io/Games.jl/latest/lib/repeated_game.html).

**Comment by oyamad** [comment]
Remove the type declarations from the header. For example:

```
covariance_game{N}([rng::AbstractRNG], nums_actions::NTuple{N,Int}, 
                   rho::Real)
```

should be

```
covariance_game{N}([rng], nums_actions, rho)
```

or

```
covariance_game{N}([rng=GLOBAL_RNG], nums_actions, rho)
```

The type declarations are provided in the Arguments section.
